version: "3.7"
services:
  api:
    build:
      args:
        user: root
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: apibolasoft
    container_name: apibolasoft-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - apibolasoft

  nginx:
    image: nginx:alpine
    container_name: apibolasoft-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - apibolasoft

networks:
  apibolasoft:
    driver: bridge