version: "3.7"
services:
  api:
    build:
      args:
        user: root
        #uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: backendapi
    container_name: backendapi-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - backendapi
    environment:
      CONTAINER_ROLE: app

  nginx:
    image: nginx:alpine
    container_name: backendapi-nginx
    restart: unless-stopped
    ports:
      - "5002:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - backendapi

  scheduler:
    image: backendapi
    container_name: backendapi-scheduler
    depends_on:
      - api
    restart: unless-stopped
    working_dir: /var/www/
    volumes: 
      - ./:/var/www
    networks:
      - backendapi
    environment:
      CONTAINER_ROLE: scheduler
 

  queue:
    image: backendapi
    container_name: backendapi-queue
    depends_on:
      - api
    volumes:
      - ./:/var/www
    environment:
      CONTAINER_ROLE: queue

networks:
  backendapi:
    driver: bridge
