version: "3.7"
services:
  app:
    build:
      args:
        user: root
        #uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: bola
    container_name: bola-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bola

  nginx:
    image: nginx:alpine
    container_name: bola-nginx
    restart: unless-stopped
    ports:
      - "5001:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - bola

networks:
  bola:
    driver: bridge